### ISSUE TITLE
Importing Modules. 

### ISSUE THREAD

**Issue by vporta** [conniejmiller/SSW555tm092017Fall#28]
It's not a huge problem, but we shouldn't be importing all functions from a module:
```
from helpers import *
from validate import *
from display import *
```

I think it's bad practice for security and performance reasons.

**Comment by conniejmiller** [comment]
being new to Python, I didn't know there were any other options until I saw your code last week and this.  I'm good with including only what we need.

**Comment by ryancoppa** [comment]
I agree, it's good practice to be concise in the import statements

**Comment by conniejmiller** [comment]
addressed in current merge request
