### ISSUE TITLE
US35, US36 not working

### ISSUE THREAD

**Issue by conniejmiller** [conniejmiller/SSW555tm092017Fall#32]
These routines are not printing errors with the output.  The tests written work because there is only one record in the sample and the output is not being tested.

**Comment by vporta** [comment]
The user story doesn't state to print errors.

**Comment by conniejmiller** [comment]
Sorry, not errors, it's not printing the recent births and deaths.  It does not meet the requirements of the story nor the assignment.
It returns ONE error....and so the tests you've constructed works but when called from the project.py, it does not display anything.

**Comment by vporta** [comment]
Odd, it was printing when I tried it. I'll test it in a few hours when I get home. 

Vincent

**Comment by vporta** [comment]
My new output: 
US36: LIST RECENT DEATHS: Bob /Jones/ | 2017-10-20 00:00:00
US35: LIST RECENT BIRTHS: Andrew /Stewart/ | 2017-10-20 00:00:00

**Comment by conniejmiller** [comment]
this date format differs from all other dates we display.
These routines only print the first recent birth or date in the file, not all.  You need better test data.

**Comment by vporta** [comment]
It prints only one because there is only one recent birth and death in the testing.ged.... 

Vincent

**Comment by conniejmiller** [comment]
what if the prof runs it against a file with more than one?  this code does not meet the requirements.  you've created a test file that looks like it works....but it doesn't really.

**Comment by conniejmiller** [comment]
The problem is it returns when it finds the first date that meets the criteria.  You need to restructure this so it always goes thru the entire input file.

**Comment by vporta** [comment]
@conniejmiller  I added new test data. I see what you are saying: It returns a list of names now, but it always printed more than one name of a recent birth or death. 

"you've created a test file that looks like it works....but it doesn't really." I am not entirely sure what you are suggesting. 
  
Branch is updated.
